## TensorFlow 2 quickstart for beginners
https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb#scrollTo=3wF5wszaj97Y

In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.9.1


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 6s 1us/step


In [8]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [9]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.02525551,  0.0170747 ,  0.3575266 ,  0.20626806,  0.26149654,
         0.64457846, -0.1841948 , -0.40209675, -0.14616542,  0.05649845]],
      dtype=float32)

In [10]:
tf.nn.softmax(predictions).numpy()

array([[0.09053026, 0.08979268, 0.12621103, 0.10849421, 0.11465473,
        0.16817535, 0.07342276, 0.0590469 , 0.07626875, 0.09340335]],
      dtype=float32)

In [11]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [12]:
loss_fn(y_train[:1], predictions).numpy()

1.7827481

In [13]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [14]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 9s 4ms/step - loss: 0.3002 - accuracy: 0.9126
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1423 - accuracy: 0.9567
Epoch 3/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1069 - accuracy: 0.9676
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0869 - accuracy: 0.9736
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0755 - accuracy: 0.9759


In [15]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0712 - accuracy: 0.9781 - 820ms/epoch - 3ms/step


[0.07116793841123581, 0.9781000018119812]

In [16]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [17]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.52105714e-08, 1.99040517e-09, 6.84519136e-06, 1.65145902e-04,
        2.60800659e-10, 4.12577954e-08, 7.83135848e-11, 9.99793828e-01,
        1.54011889e-06, 3.25076180e-05],
       [1.41977665e-07, 6.24139328e-04, 9.99210835e-01, 1.59349540e-04,
        2.67039307e-11, 5.68402129e-07, 8.09139493e-08, 2.56789607e-11,
        4.93609150e-06, 4.30284280e-12],
       [1.52011495e-07, 9.98843551e-01, 2.07462974e-04, 1.34644306e-05,
        2.96657799e-05, 4.69485985e-06, 5.60339686e-06, 5.85582864e-04,
        3.09113006e-04, 7.52024050e-07],
       [9.99963045e-01, 5.44534529e-10, 9.69849589e-06, 3.05946712e-09,
        4.31283325e-07, 1.32796481e-06, 2.17037723e-05, 1.44702096e-06,
        1.26976456e-08, 2.32320781e-06],
       [9.90288527e-07, 1.89885295e-11, 1.68026156e-06, 6.47717269e-10,
        9.97846246e-01, 8.46092441e-09, 6.13841223e-07, 1.07372725e-05,
        1.42585490e-08, 2.13988149e-03]], dtype=float32)>