In [93]:
### ww3.nd.edu

In [33]:
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [34]:
import pandas as pd
import numpy as np

In [35]:
data_file = './data/massey.csv'
df = pd.read_csv(data_file, index_col=0)
df.head()

Badin Farley  Lyons McGlinn Pangborn
equipos                                       
Badin         -  37-82  51-54   37-68    30-75
Farley    82-37      -  64-46   55-47    57-37
Lyons     54-51  46-64      -   37-35    33-60
McGlinn   68-37  47-55  35-37       -    44-82
Pangborn  75-30  37-57  60-33   82-44        -

In [36]:
print(df.columns)

Index(['Badin', 'Farley', 'Lyons', 'McGlinn', 'Pangborn'], dtype='object')


In [38]:
rows = []
for i in df.index:
    puntos = 0
    for c in df.columns:
        if i == c: continue
        score = df.loc[i,c]
        ssplit = score.split('-')
        puntos = puntos + int(ssplit[0])-int(ssplit[1])
    rows.append([i,puntos])
df2 = pd.DataFrame(rows, columns = ['equipos', 'PointDiff'])
df2

equipos  PointDiff
0     Badin       -124
1    Farley         91
2     Lyons        -40
3   McGlinn        -17
4  Pangborn         90

In [40]:
df = pd.merge(df, df2, left_on='equipos', right_on='equipos', how='left')
df

equipos  Badin Farley  Lyons McGlinn Pangborn  PointDiff
0     Badin      -  37-82  51-54   37-68    30-75       -124
1    Farley  82-37      -  64-46   55-47    57-37         91
2     Lyons  54-51  46-64      -   37-35    33-60        -40
3   McGlinn  68-37  47-55  35-37       -    44-82        -17
4  Pangborn  75-30  37-57  60-33   82-44        -         90

In [42]:
data_file = './data/massey.csv'
df3 = pd.read_csv(data_file, index_col=0)
df3.head()

Badin Farley  Lyons McGlinn Pangborn
equipos                                       
Badin         -  37-82  51-54   37-68    30-75
Farley    82-37      -  64-46   55-47    57-37
Lyons     54-51  46-64      -   37-35    33-60
McGlinn   68-37  47-55  35-37       -    44-82
Pangborn  75-30  37-57  60-33   82-44        -

In [87]:
X = np.array([
            [1, -1,  0,  0,  0],
            [1,  0, -1,  0,  0],
            [1,  0,  0, -1,  0],
            [1,  0,  0,  0, -1],
            [0,  1, -1,  0,  0],
            [0,  1,  0, -1,  0],
            [0,  1,  0,  0, -1],
            [0,  0,  1, -1,  0],
            [0,  0,  1,  0, -1],
            [0,  0,  0,  1, -1]
            ])
B = np.array(
    [-45,-3,-31,-45,18,8,20,2,-27,-38]
    )
Xty = np.array([-124,91,-40,-17,90])

In [88]:
Xt = np.transpose(X)
Xt

array([[ 1,  1,  1,  1,  0,  0,  0,  0,  0,  0],
       [-1,  0,  0,  0,  1,  1,  1,  0,  0,  0],
       [ 0, -1,  0,  0, -1,  0,  0,  1,  1,  0],
       [ 0,  0, -1,  0,  0, -1,  0, -1,  0,  1],
       [ 0,  0,  0, -1,  0,  0, -1,  0, -1, -1]])

In [89]:
M = np.matmul(Xt,X)
M

array([[ 4, -1, -1, -1, -1],
       [-1,  4, -1, -1, -1],
       [-1, -1,  4, -1, -1],
       [-1, -1, -1,  4, -1],
       [-1, -1, -1, -1,  4]])

In [92]:
# no son los resultados
X = np.linalg.inv(M).dot(Xty)
print(X)

[-16.  32.   8.   8.  32.]
